version: '3'

services:
  app:
    container_name: chatgpt-web
    image: rexwzh/chatgpt-web:v0.0.2 # 总是使用latest,更新时重新pull该tag镜像即可
    ports:
      - 3002:3002
    environment:
      # 二选一
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      # 二选一
      OPENAI_ACCESS_TOKEN: "${OPENAI_ACCESS_TOKEN}"
      # API接口地址，可选，设置 OPENAI_API_KEY 时可用
      OPENAI_API_BASE_URL: "${OPENAI_API_BASE_URL}"
      # API模型，可选，设置 OPENAI_API_KEY 时可用
      OPENAI_API_MODEL: "${OPENAI_API_MODEL}"
      # 反向代理，可选
      API_REVERSE_PROXY: "${API_REVERSE_PROXY}"
      # 访问权限密钥，可选
      AUTH_SECRET_KEY: "${AUTH_SECRET_KEY}"
      # 每小时最大请求次数，可选，默认无限
      MAX_REQUEST_PER_HOUR: "${MAX_REQUEST_PER_HOUR}"
      # 超时，单位毫秒，可选
      TIMEOUT_MS: "${TIMEOUT_MS}"
      # Socks代理，可选，和 SOCKS_PROXY_PORT 一起时生效
      SOCKS_PROXY_HOST: "${SOCKS_PROXY_HOST}"
      # Socks代理端口，可选，和 SOCKS_PROXY_HOST 一起时生效
      SOCKS_PROXY_PORT: "${SOCKS_PROXY_PORT}"
      # Socks代理用户名，可选，和 SOCKS_PROXY_HOST & SOCKS_PROXY_PORT 一起时生效
      SOCKS_PROXY_USERNAME: "${SOCKS_PROXY_USERNAME}"
      # Socks代理密码，可选，和 SOCKS_PROXY_HOST & SOCKS_PROXY_PORT 一起时生效
      SOCKS_PROXY_PASSWORD: "${SOCKS_PROXY_PASSWORD}"
      # HTTPS_PROXY 代理，可选
      HTTPS_PROXY: "${HTTPS_PROXY}"
    env_file:
      - .env